In [1]:
from model.model import ConvModel, SimCLR
import argparse
import torch
import torch.backends.cudnn as cudnn
from torchvision import models
from torchvision import transforms, datasets


In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    cudnn.deterministic = True
    cudnn.benchmark = True
    gpu_index = 0
else:
    device = torch.device('cpu')
    gpu_index = -1


In [10]:
composed_transforms = transforms.Compose([
        transforms.GaussianBlur(kernel_size=3),
      transforms.RandomRotation(degrees=10), # TODO
      transforms.RandomGrayscale(p=0.2),
      transforms.ToTensor()])

In [27]:
train_dataset_1 = datasets.CIFAR10('./datasets', train=True,
                               transform=composed_transforms,
                               download=True)
train_dataset_2 = datasets.CIFAR10('./datasets', download=True, train=True, transform=transforms.ToTensor())
g = torch.Generator()
g.manual_seed(0)

Files already downloaded and verified
Files already downloaded and verified


In [28]:
train_loader_1 = torch.utils.data.DataLoader(
    train_dataset_1, batch_size=256, shuffle=False,
     pin_memory=True, drop_last=True, generator=g)
train_loader_2 = torch.utils.data.DataLoader(train_dataset_2, batch_size=256, shuffle=True, pin_memory=True, drop_last=True, generator=g)

In [29]:
model = ConvModel(out_dim=10, dataset='CIFAR10')

model.load_state_dict(torch.load('saved_models/model_final_cifar10_200_epochs.pth'))


C:\Users\kacpe\DataspellProjects\SimCLRPytorch\venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\kacpe\DataspellProjects\SimCLRPytorch\venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


<All keys matched successfully>

In [30]:
optimizer = torch.optim.Adam(model.parameters(), 0.0003, weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=len(train_loader_1), eta_min=0,
                                                       last_epoch=-1)

with torch.cuda.device(gpu_index):
    simclr = SimCLR(model=model, optimizer=optimizer, scheduler=scheduler, device=device, epochs=200, log_every_n_steps=100)
    simclr.train(train_loader_1, shuffle=True)

NameError: name 'train_loader' is not defined

In [9]:
torch.save(model.state_dict(), 'saved_models/model_final_cifar10_200_epochs.pth')

In [31]:
model

ConvModel(
  (resnet_model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, tr

In [32]:
model.backbone.fc = torch.nn.Sequential(
    torch.nn.Linear(in_features=512, out_features=128, bias=True),
    torch.nn.ReLU(inplace=True),
    # torch.nn.BatchNorm1d(128),
    torch.nn.Linear(in_features=128, out_features=10, bias=True),
)


In [33]:
model.backbone.requires_grad_(False)
model.backbone.fc.requires_grad_(True)

for parameter in model.backbone.named_parameters():
    print(f'{parameter[0]}: {parameter[1].requires_grad}')


conv1.weight: False
bn1.weight: False
bn1.bias: False
layer1.0.conv1.weight: False
layer1.0.bn1.weight: False
layer1.0.bn1.bias: False
layer1.0.conv2.weight: False
layer1.0.bn2.weight: False
layer1.0.bn2.bias: False
layer1.1.conv1.weight: False
layer1.1.bn1.weight: False
layer1.1.bn1.bias: False
layer1.1.conv2.weight: False
layer1.1.bn2.weight: False
layer1.1.bn2.bias: False
layer2.0.conv1.weight: False
layer2.0.bn1.weight: False
layer2.0.bn1.bias: False
layer2.0.conv2.weight: False
layer2.0.bn2.weight: False
layer2.0.bn2.bias: False
layer2.0.downsample.0.weight: False
layer2.0.downsample.1.weight: False
layer2.0.downsample.1.bias: False
layer2.1.conv1.weight: False
layer2.1.bn1.weight: False
layer2.1.bn1.bias: False
layer2.1.conv2.weight: False
layer2.1.bn2.weight: False
layer2.1.bn2.bias: False
layer3.0.conv1.weight: False
layer3.0.bn1.weight: False
layer3.0.bn1.bias: False
layer3.0.conv2.weight: False
layer3.0.bn2.weight: False
layer3.0.bn2.bias: False
layer3.0.downsample.0.weight: 

In [34]:
optimizer = torch.optim.Adam(model.parameters(), 0.0003, weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=len(train_loader_2), eta_min=0,
                                                       last_epoch=-1)
with torch.cuda.device(gpu_index):
    simclr = SimCLR(model=model, optimizer=optimizer, scheduler=scheduler, device=device, epochs=200, log_every_n_steps=100)
    simclr.train(train_loader_2, shuffle=False)


  0%|          | 0/195 [00:00<?, ?it/s]C:\Users\kacpe\DataspellProjects\SimCLRPytorch\venv\lib\site-packages\torch\optim\lr_scheduler.py:807: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "
100%|██████████| 195/195 [00:07<00:00, 26.35it/s]


In [35]:
test_dataset = datasets.CIFAR10('./datasets', download=True, train=False, transform=transforms.ToTensor())
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=256, shuffle=True, pin_memory=True, drop_last=True, generator=g)

Files already downloaded and verified


In [38]:
import logging
from torch.utils.tensorboard import SummaryWriter
import os
from model.model import accuracy
from tqdm import tqdm

total = 0
running_accuracy = 0
n_iter = 0
writer = SummaryWriter()
logging.basicConfig(filename=os.path.join(writer.log_dir, 'training.log'), level=logging.DEBUG)
criterion = torch.nn.CrossEntropyLoss().to(device)

with torch.no_grad():
    for images, labels in tqdm(test_loader):
        images = torch.cat((images, images), dim=0)
        labels = torch.cat((labels, labels), dim=0)

        images = images.to(device)
        labels = labels.to(device)
        output = model(images)
        loss = criterion(output, labels)
        top1, top5 = accuracy(output, labels, topk=(1, 5))
        writer.add_scalar('loss', loss, global_step=n_iter)
        writer.add_scalar('acc/top1', top1[0], global_step=n_iter)
        writer.add_scalar('acc/top5', top5[0], global_step=n_iter)
        n_iter += 1
        print(top1)

 10%|█         | 4/39 [00:00<00:03, 11.32it/s]

tensor([32.0312], device='cuda:0')
tensor([40.2344], device='cuda:0')
tensor([37.5000], device='cuda:0')
tensor([37.1094], device='cuda:0')
tensor([38.6719], device='cuda:0')
tensor([35.1562], device='cuda:0')


 26%|██▌       | 10/39 [00:00<00:01, 17.73it/s]

tensor([32.0312], device='cuda:0')
tensor([35.5469], device='cuda:0')
tensor([37.5000], device='cuda:0')
tensor([36.7188], device='cuda:0')
tensor([37.1094], device='cuda:0')


 33%|███▎      | 13/39 [00:00<00:01, 19.17it/s]

tensor([35.1562], device='cuda:0')
tensor([38.6719], device='cuda:0')
tensor([33.5938], device='cuda:0')
tensor([34.3750], device='cuda:0')
tensor([38.2812], device='cuda:0')


 49%|████▊     | 19/39 [00:01<00:00, 20.99it/s]

tensor([36.3281], device='cuda:0')
tensor([40.2344], device='cuda:0')
tensor([37.5000], device='cuda:0')
tensor([31.6406], device='cuda:0')
tensor([38.6719], device='cuda:0')


 64%|██████▍   | 25/39 [00:01<00:00, 21.99it/s]

tensor([33.5938], device='cuda:0')
tensor([32.0312], device='cuda:0')
tensor([35.1562], device='cuda:0')
tensor([36.7188], device='cuda:0')
tensor([34.3750], device='cuda:0')


 79%|███████▉  | 31/39 [00:01<00:00, 22.29it/s]

tensor([35.1562], device='cuda:0')
tensor([32.4219], device='cuda:0')
tensor([38.2812], device='cuda:0')
tensor([36.7188], device='cuda:0')
tensor([35.5469], device='cuda:0')


 87%|████████▋ | 34/39 [00:01<00:00, 22.57it/s]

tensor([33.2031], device='cuda:0')
tensor([35.5469], device='cuda:0')
tensor([33.2031], device='cuda:0')
tensor([41.0156], device='cuda:0')
tensor([33.9844], device='cuda:0')
tensor([29.6875], device='cuda:0')


100%|██████████| 39/39 [00:01<00:00, 20.01it/s]

tensor([39.0625], device='cuda:0')
tensor([33.9844], device='cuda:0')
